apiVersion: batch/v1
kind: Job
metadata:
  name: echo
spec:
  template:
    spec:
      containers:
      - name: echo
        image: alpine:3.19.1
        command: ["/bin/echo",  "-e", "cool kubernetes job"]
      restartPolicy: Never
  backoffLimit: 4