on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy
        run: |
          kubectl apply -f kubernetes/namespace.yml
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/service.yml
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: 'maximilian-volk'
          secret-name: 'regcred'
          container-registry-url: 'ghcr.io'
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        id: create-secret